name: newAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  name : 'Sanjay'
jobs:
  mainjob:
    name: 'Print my name:'
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: checkout code
      run: |
        echo "May name is ${{ env.name }}"
        echo  "thank you"
      
      
    
     










